# Generated by Django 3.2.16 on 2022-12-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='uploadfiles/')),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=200)),
                ('upoload_layer', models.BooleanField(default=False)),
                ('dump_layer', models.BooleanField(default=False)),
                ('transformation_layer', models.BooleanField(default=False)),
                ('records_inserted', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
