# Generated by Django 3.2.16 on 2023-01-06 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('file', models.FileField(default=None, upload_to='uploadfiles/')),
                ('file_name', models.CharField(default=None, max_length=100, null=True)),
                ('file_type', models.CharField(blank=True, max_length=200, null=True)),
                ('upoload_layer', models.BooleanField(blank=True, default=False, null=True)),
                ('dump_layer', models.BooleanField(blank=True, default=False, null=True)),
                ('transformation_layer', models.BooleanField(blank=True, default=False, null=True)),
                ('records_inserted', models.BigIntegerField(blank=True, null=True)),
                ('valid_file_path', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
