# Generated by Django 4.1.4 on 2022-12-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file',
            field=models.FileField(null=True, upload_to='uploadfiles/'),
        ),
    ]
