# Generated by Django 3.2.16 on 2023-01-03 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_upload_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='dump_layer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='record_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='records_inserted',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='transformation_layer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='upoload_layer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
