# Generated by Django 3.2.16 on 2023-01-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20230103_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='valid_file_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='upload',
            name='dump_layer',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploadfiles/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='upload',
            name='records_inserted',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='transformation_layer',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='upoload_layer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
