# Generated by Django 3.2.16 on 2023-01-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20230108_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='project_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
