# Generated by Django 3.2.16 on 2023-01-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20230104_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(default=None, upload_to='uploadfiles/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
