# Generated by Django 3.2.16 on 2023-01-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_upload_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(default=None, max_length=100, null=True)),
                ('user_name', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.CharField(default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_source', models.CharField(blank=True, max_length=200, null=True)),
                ('column_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_transformation', models.BooleanField(blank=True, default=False, null=True)),
                ('currency_transformation', models.BooleanField(blank=True, default=False, null=True)),
                ('roundoff_transformation', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
