# Generated by Django 3.2.16 on 2023-01-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_alter_project_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
