# Generated by Django 3.2.16 on 2023-01-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_alter_project_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
    ]
