# Generated by Django 3.2.16 on 2023-01-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_remove_project_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataqualitycheck',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
