# Generated by Django 3.2.16 on 2023-01-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_auto_20230113_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
