# Generated by Django 3.2.16 on 2023-01-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
