# Generated by Django 3.2.16 on 2023-01-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0017_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
