# Generated by Django 3.2.16 on 2023-01-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0018_auto_20230113_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('database_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='datasource',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='project_id',
            field=models.IntegerField(),
        ),
    ]
