# Generated by Django 3.2.16 on 2023-01-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0020_auto_20230118_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLogs',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('project_name', models.IntegerField(blank=True, null=True)),
                ('data_source', models.IntegerField(blank=True, null=True)),
                ('query_statement', models.CharField(blank=True, max_length=1000, null=True)),
                ('target_table', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='datasource',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='project_id',
            field=models.IntegerField(),
        ),
    ]
