# Generated by Django 3.2.16 on 2023-01-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0021_auto_20230127_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querylogs',
            old_name='project_name',
            new_name='project_id',
        ),
        migrations.AlterField(
            model_name='datasource',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='project_id',
            field=models.BigIntegerField(),
        ),
    ]
