# Generated by Django 3.2.16 on 2023-01-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0022_auto_20230127_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
