# Generated by Django 3.2.16 on 2023-01-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0023_auto_20230131_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
