# Generated by Django 3.2.16 on 2023-02-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0026_auto_20230131_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='filterSymbol',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='datasource',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
