# Generated by Django 3.2.16 on 2023-02-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0031_auto_20230202_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDataSource',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
                ('table_records', models.IntegerField(blank=True, null=True)),
                ('total_records', models.IntegerField(blank=True, null=True)),
                ('final_data_file_generate', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_source_list', to='upload.project')),
            ],
        ),
    ]
